services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: heritage_sharing_user
      POSTGRES_PASSWORD: heritage_sharing_password
      POSTGRES_DB: heritage_sharing_development
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  default: &default
    build:
      context: .
      target: dev
    image: heritage_sharing:dev
    container_name: rails-template-dev
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle:cached
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_NAME:
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  dev: &dev
    <<: *default
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

  vite:
    build: .
    command: bin/vite dev --clobber
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/rails
    tty: true
    stdin_open: true

volumes:
  postgres:
  bundle:
